### ISSUE TITLE
"No module named propsys" with SpiderOak installed

### ISSUE THREAD

**Issue by johnwoltman** [mcedit/mcedit2#21]
When I run the alpha1 version, I get a crashed ending with ImportError: No module named propsys.  The full output is at https://gist.github.com/johnwoltman/dda6a8448d60a8681186

I'm running minecraft 1.8.1 on Java 8 on Windows 7 64-bit.

**Comment by codewarrior0** [comment]
That doesn't look like my build. Where did you download it from?

**Comment by johnwoltman** [comment]
From the mcedit's github release page.

**Comment by codewarrior0** [comment]
All right. This error shouldn't even be coming up since I don't use py2exe. I'll reload my entire python installation before doing the next build, and then I'll ask you to try that one.

**Comment by Terminator468** [comment]
Yeah im having the same problem please help

**Comment by Terminator468** [comment]
i really need mcedit and its not working please tell me how to fix it and fast

**Comment by Terminator468** [comment]
PLEASE

**Comment by johnwoltman** [comment]
Then use the old stable version at http://khroki.github.io/MCEdit-Unified/

**Comment by Terminator468** [comment]
I tried it it just deleted everything in the world

On Sunday, February 15, 2015, J Woltman <notifications@github.com> wrote:

> Then use the old stable version at http://khroki.github.io/MCEdit-Unified/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcedit/mcedit2/issues/21#issuecomment-74416540>.
>


-- 

      Sincerely,
       Jude Nelson

**Comment by hmksq** [comment]
I am really hyped about MCEdit 2.0 but I can't run it. :(

**Comment by Terminator468** [comment]
Yeah, sorry about that. I hope you can get it running!

On Saturday, March 21, 2015, Humaid AlQassimi <notifications@github.com>
wrote:

> I am really hyped about MCEdit 2.0 but I can't run it. :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcedit/mcedit2/issues/21#issuecomment-84399155>.
>


-- 

      Sincerely,
       Jude Nelson

**Comment by hmksq** [comment]
I got the "Technology Demo" version running, I am amazed even that version crashed a lot.
I thought I could fix the error by install py2exe, but it still didn't work.

We will have to wait or just use the older version. :)
Date: Sat, 21 Mar 2015 10:26:47 -0700

**Comment by codewarrior0** [comment]
Haven't heard anything more, assuming it's fixed in the newer builds.

**Comment by johnwoltman** [comment]
I haven't tried it an while.  I was waiting for a new binary release on the GitHub page before I tried again.  I uninstalled Python3 (which I use for work) in case that was causing problems, but that didn't solve issue.

When a new release is published I'll give it a go.  Thanks for all your hard work :)

**Comment by johnwoltman** [comment]
I just tried again on a different computer, this time on a fresh 64-bit Windows 8.1 installation (only a couple days old).  The log is basically identical to what I posted in my initial gist, just with different paths since this is a new install.  I downloaded MCEdit version 2.0.0alpha-232.  My initial bug report was filed on a system with Intel graphics, this new computer has AMD graphics.

In case it's helpful I put the new log here: https://gist.github.com/johnwoltman/e1e5a3abe9cdcb39f1df

**Comment by codewarrior0** [comment]
That's odd. `boot_com_servers.py` is part of py2exe, which I used to use for MCEdit 1.0. Since your first report I've completely reinstalled python and all of my virtualenvs and I'm 100% confident I don't have a `boot_com_servers.py` anywhere on my computer - it doesn't even appear in the TOC files used by pyinstaller, so it can't be part of the MCEdit 2.0.0alpha-232 you downloaded.

I've got a hunch you've got an environment variable set from the work you did with Python 3. Could you run `cmd.exe` and type in `echo %PYTHONPATH%`? 

Honestly, PyInstaller .exes should ignore that environ since all the modules it needs are packed into the exe, so if not that's a bug in PyInstaller.

**Comment by codewarrior0** [comment]
The only thing I could find related to that error is this thread about Calibre, an e-book reader written in Python using Qt:

http://www.mobileread.com/forums/showthread.php?t=220500

**Comment by johnwoltman** [comment]
Very strange.  On my Windows 8 machine I have never installed Python.  However, I do have SpiderOak (an online syncing/cloud storage program) installed, which I believe is written in Python & Qt.  I uninstalled SpiderOak, and now MCEdit 2 launches.

Is there some workaround I can try so that I can have SpiderOak and MCEdit installed?

**Comment by codewarrior0** [comment]
I don't know of any workaround. After installing SpiderOak, I am still unable to reproduce the problem.

**Comment by codewarrior0** [comment]
Hmm. The only thing I can imagine is that this is related to SpiderOak's shell extension, which is registered as some kind of COM server. As a side effect of some part of MCEdit's startup code, the SpiderOak `shell-extension.dll` gets loaded into MCEdit's process and fails to find its own library files for whatever reason. 

Do you need the shell extension? Try installing SpiderOak without "Shell Integration".

**Comment by codewarrior0** [comment]
Aha, that must be what's happening! I installed SpiderOak with the Shell Integration enabled, then started up MCEdit, brought up the "Open Another World" dialog to get an Explorer file dialog. When I right clicked on a file in there, it tried to load the shell extension and I got the `ImportError: No module named propsys` error!

I'm not sure what the exact problem is, but now I know enough to start talking to the py2exe devs about it. You should be able to uninstall SpiderOak's shell integration as a workaround.

**Comment by Terminator468** [comment]
Well, I think that's the problem. I have spider oak on my computer too. I'm
glad you guys could figure that out! If there's no way you can fix that, be
sure to note that on the download page or something so that this doesn't
happen again.

On Saturday, April 25, 2015, David Vierra <notifications@github.com> wrote:

> Aha, that must be what's happening! I installed SpiderOak with the Shell
> Integration enabled, then started up MCEdit, brought up the "Open Another
> World" dialog to get an Explorer file dialog. When I right clicked on a
> file in there, it tried to load the shell extension and I got the ImportError:
> No module named propsys error!
>
> I'm not sure what the exact problem is, but now I know enough to start
> talking to the py2exe devs about it. You should be able to uninstall
> SpiderOak's shell integration as a workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcedit/mcedit2/issues/21#issuecomment-96231683>.
>


-- 

      Sincerely,
       Jude Nelson

**Comment by johnwoltman** [comment]
I reinstalled SpiderOak, this time without the shell integration, and MCEdit 2 launches just fine.  I agree with @Terminator468, maybe there should be a "known issues" section that lists this issue.

**Comment by Kirby420** [comment]
Just wanted to leave this here - if you go into the options of SpiderOak and uncheck the "Enable OS Integration" checkbox, you can temporarily disable SpiderOak's menu options and resolve the bug without needing to uninstall and reinstall it.
